# Stage 1: Build
FROM maven:3.8.6-openjdk-20 AS build

WORKDIR /app

# Copy all project files to the container
COPY . .

# Build the project and skip tests
RUN mvn clean install -DskipTests

# Stage 2: Runtime
FROM openjdk:20-jdk-alpine

WORKDIR /app

# Copy the built jar file from the previous stage
COPY --from=build /app/target/employee-management-system.jar .

# Set environment variables
ENV PORT=8081

# Expose the application port
EXPOSE 8081

# Command to run the application
ENTRYPOINT ["java", "-jar", "employee-management-system.jar"]
